base_path = './'

data_path = base_path + '/data'

TR_PR = "TRANSLATION_PROVIDER"
TR_MODEL = "TRANSLATION_MODEL"
TR_API_URL = "TRANSLATION_API_URL"
TR_API_KEY = "TRANSLATION_API_KEY"

# RESPONSE GENERATION
RG_MODEL = "RESPONSE_GENERATION_MODEL"
RG_API_URL = "RESPONSE_GENERATION_API_URL"
RG_API_KEY = "RESPONSE_GENERATION_API_KEY"


